"""Oturum verilerinin yonetimi (Firefox/Cookie File import, test, temp file)."""

import contextlib
import os
import sqlite3
import uuid
from pathlib import Path

from src.browser_sessions import _detect_firefox_profiles
from src.session_store import SessionStore

ALLOWED_DOMAINS = {
    "threads.com",
    ".threads.com",
    "threads.net",
    ".threads.net",
    "instagram.com",
    ".instagram.com",
}


def _is_domain_allowed(domain: str) -> bool:
    d = domain.lower()
    return d in ALLOWED_DOMAINS or any(
        d.endswith("." + allowed) for allowed in ALLOWED_DOMAINS
    )


class SessionManager:
    def __init__(self) -> None:
        self.store = SessionStore()

        local_appdata = os.environ.get("LOCALAPPDATA")
        if not local_appdata:
            local_appdata = str(Path.home() / "AppData" / "Local")

        self.temp_dir = Path(local_appdata) / "Loadvia" / "Temp"
        self.temp_dir.mkdir(parents=True, exist_ok=True)

    def cleanup_stale_temp_files(self) -> None:
        """Kapanistan kalmis olabilecek eski session-*.txt dosyalarini temizler."""
        if not self.temp_dir.exists():
            return
        for child in self.temp_dir.iterdir():
            if (
                child.is_file()
                and child.name.startswith("session-")
                and child.name.endswith(".txt")
            ):
                try:
                    child.unlink()
                except OSError:
                    pass

    def get_session_status(self) -> str:
        """'Yok', 'Bagli', 'Yenilenmeli' gibi temel durum dondurur (şimdilik sadece Yok/Bagli)."""
        data = self.store.load_session()
        if not data:
            return "Oturum yok"
        return "Bağlı"

    def import_from_firefox(self) -> tuple[bool, str]:
        """Firefox profillerinden instagram/threads cerezlerini okuyup kaydeder."""
        profiles = _detect_firefox_profiles()
        if not profiles:
            return False, "Firefox profili bulunamadı."

        cookies_found = []
        for profile in profiles:
            if not profile.profile_path:
                continue
            db_path = profile.profile_path / "cookies.sqlite"
            if not db_path.exists():
                continue

            try:
                # URI ile read-only acarak kilitlenmeleri onlemeye calisiyoruz
                uri = f"file:{db_path.as_posix()}?mode=ro"
                with sqlite3.connect(uri, uri=True, timeout=1.0) as conn:
                    conn.row_factory = sqlite3.Row
                    cursor = conn.cursor()
                    cursor.execute(
                        "SELECT host, path, isSecure, expiry, name, value FROM moz_cookies"
                    )
                    for row in cursor.fetchall():
                        host = row["host"]
                        if _is_domain_allowed(host):
                            cookies_found.append(row)
            except Exception:  # noqa: BLE001, S110
                pass

        if not cookies_found:
            return False, "Firefox'ta Threads veya Instagram oturumu bulunamadı."

        # Netscape formatina cevir
        netscape_lines = ["# Netscape HTTP Cookie File", "# Generated by Loadvia", ""]
        for row in cookies_found:
            host = row["host"]
            path = row["path"] or "/"
            is_secure = "TRUE" if row["isSecure"] else "FALSE"
            expiry = str(row["expiry"] or 0)
            name = row["name"]
            value = row["value"]

            # domain_flag: TRUE if domain starts with dot, FALSE otherwise
            domain_flag = "TRUE" if host.startswith(".") else "FALSE"

            line = (
                f"{host}\t{domain_flag}\t{path}\t{is_secure}\t{expiry}\t{name}\t{value}"
            )
            netscape_lines.append(line)

        self.store.save_session("\n".join(netscape_lines) + "\n")
        return True, "Firefox oturumu başarıyla içe aktarıldı."

    def import_from_cookie_file(self, file_path: Path | str) -> tuple[bool, str]:
        """Netscape dosyasindan sadece izin verilen alan adlarini alip kaydeder."""
        path = Path(file_path)
        if not path.exists():
            return False, "Dosya bulunamadı."

        netscape_lines = ["# Netscape HTTP Cookie File", "# Imported by Loadvia", ""]
        valid_cookie_count = 0

        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    stripped = line.strip()
                    if not stripped or stripped.startswith("#"):
                        continue

                    parts = stripped.split("\t")
                    if len(parts) >= 7:
                        host = parts[0]
                        if _is_domain_allowed(host):
                            netscape_lines.append(stripped)
                            valid_cookie_count += 1

            if valid_cookie_count == 0:
                return False, "Dosyada uygun Threads veya Instagram oturumu bulunamadı."

            self.store.save_session("\n".join(netscape_lines) + "\n")
            return True, "Çerez dosyası başarıyla içe aktarıldı."
        except Exception as exc:  # noqa: BLE001
            return False, f"Dosya okunamadı: {exc}"

    def remove_session(self) -> None:
        self.store.delete_session()

    def test_session(self) -> str:
        """
        Oturumun gecerliligini test eder.
        Dondurecegi degerler: 'Gecerli', 'Gecersiz', 'Oturum Yok', 'Ag Hatasi'
        Bu test icin aslinda kucuk bir request (urllib ile instagram anasayfasina veya threads'e) yapilabilir.
        Ancak basitce cookie iceriginde ds_user_id veya sessionid var mi diye de bakilabilir.
        Simdilik 'sessionid' cookie'si var mi diye icerigine bakalim. (Ag testi karmasikligi engellemek icin)
        """
        data = self.store.load_session()
        if not data:
            return "Oturum Yok"

        if "sessionid" in data:
            return "Geçerli"
        else:
            return "Geçersiz"

    @contextlib.contextmanager
    def create_temp_cookiefile(self):
        """
        yt-dlp icin gecici cookiefile olusturur ve yields eder.
        Kullanim:
        with session_mgr.create_temp_cookiefile() as cookie_path:
            if cookie_path:
                ydl_opts['cookiefile'] = cookie_path
        """
        data = self.store.load_session()
        if not data:
            yield None
            return

        temp_file = self.temp_dir / f"session-{uuid.uuid4().hex}.txt"

        try:
            with open(temp_file, "w", encoding="utf-8") as f:
                f.write(data)

            yield str(temp_file)
        finally:
            if temp_file.exists():
                try:
                    temp_file.unlink()
                except OSError:
                    pass
